# Generated by Django 5.0.4 on 2024-04-26 09:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0003_user_delete_userprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="contact",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
