# Generated by Django 5.0.4 on 2024-04-26 10:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0005_userprofile_delete_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="contact",
        ),
    ]
